name: Lint

on:
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'eslint.config.js'
      - '.eslintrc*'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'eslint.config.js'
      - '.eslintrc*'
      - '.github/workflows/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Type-check and ESLint
        run: yarn lint:ci
      - name: Build
        run: yarn build
